#!/bin/sh

mkd() { mkdir -p "$1"; cd "$1" }

# Google it
google() {
  local term="$@"
  local url="http://www.google.com/search?q=${term// /+}"
  $BROWSER "$url"
}

# https://coderwall.com/p/r2g2rq
todo() {
  git commit --allow-empty -m "TODO: $*"
}

cleanup() {
  sudo rm -rfv /Volumes/*/.Trashes
  sudo rm -rfv ~/.Trash
  sudo rm -rfv /private/var/log/asl/*.asl
  sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'
}

function web_server() {
	local port="${1:-8000}";
	sleep 1 && open "http://localhost:${port}/" &
	python -m http.server ${port}
}

function tree_x() {
	tree -aC -I '.git|node_modules|bower_components|_build' --dirsfirst "$@" | less -FRNX;
}
