onboarding = false
[theme]
name = "dracula"

[ui.toast.clipboard]
position = "top-right"

[ui.toast]
delivery = "system"

[ui]
show_agent_labels_on_pane_borders = true

agent_panel_sort = "spaces"
[experimental]
switch_ascii_input_source_in_prefix = true
