
[tools]
"aqua:elixir-lang/expert" = "latest"
"npm:typescript" = "latest"
ast-grep = "latest"
awscli = "latest"
bat = "latest"
bun = "latest"
cmake = "latest"
codex = "latest"
difftastic = "latest"
dust = "latest"
elixir = "main-otp-28"
emsdk = "latest"
erlang = "latest"
eza = "latest"
fd = "latest"
flyctl = "latest"
fzf = "latest"
gh = "latest"
git-cliff = "latest"
git-lfs = "latest"
glow = "latest"
go = "latest"
jq = "latest"
just = "latest"
lazygit = "latest"
lua = "latest"
lua-language-server = "latest"
neovim = "stable"
node = "latest"
pnpm = "latest"
python = "3"
rust = { version = "latest", components = "rust-src,rust-analyzer,rustfmt" }
stylua = "latest"
terraform = "latest"
tree-sitter = "0.26.6"
typos = "latest"
uv = "latest"
vercel = "latest"
yazi = "latest"
zig = "latest"
zoxide = "latest"
